import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  black: {color: 'black'},
  MainContainer: {
    marginHorizontal: 12,
    justifyContent: 'flex-start',
    height: '100%',
  },
  NameBell: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: -10,
  },
  BlueCircle: {
    position: 'relative',
    width: 35,
    height: 35,
    borderRadius: 35,
    backgroundColor: '#14245b',
    alignContent: 'flex-end',
    marginTop: 15,
  },
  Bell: {
    position: 'absolute',
    top: 5,
    left: 5,
    width: 25,
    height: 25,
  },
  Title: {
    color: 'black',
    fontSize: 30,
    fontWeight: 'bold',
    paddingRight: 35,
  },
  Form: {
    marginTop: 20,
  },
  scanBorder: {
    width: 53,
    height: 53,
    // backgroundColor: 'red',
    backgroundColor: '#e9e9ebfa',
    marginLeft: 15,
    borderRadius: 7,
    // flex: 1,
  },
  scan: {
    width: 30,
    height: 30,
    top: 11,
    left: 11,
  },
  Offers: {
    backgroundColor: '#14245b',
    height: 175,
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    // paddingLeft: 30,
    paddingTop: 5,
    marginVertical: 25,
  },
  whiteText: {
    color: 'white',
    fontSize: 30,
    fontWeight: '500',
  },
  UniquePercent: {
    color: '#fcbd48',
    fontSize: 30,
    fontWeight: '500',
  },
  FinctionalCharacter: {
    flexDirection: 'column-reverse',
    width: 140,
    height: 140,
  },
  OrangeButton: {
    marginTop: 10,
    width: 110,
  },
  ProductTouch: {
    width: 80,
    height: 70,
    alignItems: 'center',
    marginHorizontal: 3,
    marginBottom: 15,
  },
  InnerTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  Product: {
    width: 50,
    height: 50,
    backgroundColor: '#e9e9ebfa',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  ProductImage: {width: 37, height: 37},
  MainSubTitle: {
    color: 'black',
    fontSize: 17,
    fontWeight: '500',
  },
  RecommendedContainer: {
    marginRight: 20,
    height: 'auto',
  },
  StarContainer: {
    position: 'absolute',
    margin: 10,
    zIndex: 1,
    backgroundColor: 'white',
    width: 50,
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    borderRadius: 5,
  },
  imgStar: {
    width: 15,
    height: 15,
  },
  imgMain: {
    borderRadius: 5,
    width: 215,
    height: 125,
    resizeMode: 'contain',
  },
  grayContainer: {
    width: 30,
    height: 30,
    backgroundColor: '#e9e9ebfa',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginTop: -10,
  },
  bag: {
    width: 15,
    height: 15,
  },
});
