import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  body: {
    justifyContent: 'flex-start',
    height: '100%',
    backgroundColor: 'white',
  },
  Header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  BlueCircle: {
    position: 'relative',
    width: 35,
    height: 35,
    borderRadius: 35,
    backgroundColor: '#14245b',
    alignContent: 'flex-end',
  },
  Bell: {
    position: 'absolute',
    top: 5,
    left: 5,
    width: 25,
    height: 25,
  },
  dropdown: {
    width: 150,
    backgroundColor: 'white',
    borderColor: 'white',
  },
  Form: {
    marginBottom: 20,
  },
  size: {
    flexDirection: 'row',
    borderColor: 'grey',
    borderWidth: 1,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  sizetext: {
    paddingHorizontal: 7,
    color: 'grey',
    fontWeight: '700',
    fontSize: 15,
  },
  Shadow: {
    shadowColor: '#bfc0be',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 30,
    marginBottom: 10,
  },
  Results: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  NumberResults: {
    fontWeight: '700',
    fontSize: 30,
    color: 'black',
  },
  TextResults: {
    fontSize: 25,
    color: 'black',
  },
  ItemsContainer: {
    marginRight: 20,
    // marginBottom: 15,
    // backgroundColor: 'red',
  },
  StarContainer: {
    backgroundColor: 'white',
    width: 45,
    height: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    borderRadius: 5,
  },
  imgStar: {
    width: 12,
    height: 12,
  },
  imgMain: {
    borderRadius: 5,
    width: 175,
    height: 175,
  },
  topIconsItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    padding: 7,
  },
  heart: {
    width: 10,
    height: 10,
  },
  whiteCircleHeart: {
    width: 25,
    height: 25,
    backgroundColor: 'white',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    // left: 15,
  },
  BottomContainer: {
    position: 'absolute',
    bottom: 0,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#14245b',
    borderRadius: 12,
    flexDirection: 'row',
    width: '90%',
    height: 45,
    marginHorizontal: 20,
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  bottomImg: {
    width: 12,
    height: 12,
  },
  verticalLine: {
    borderRightColor: '#eeeeee',
    opacity: 0.35,
    borderRightWidth: 1,
    marginVertical: 5,
  },
  ThreeContainers: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '33%',
  },
  bottomText: {
    color: 'white',
    marginStart: 5,
  },
});
